# Data Structures in Python

It's crucial that your data is in the right data structure.   

Types of structures

- Lists
- NumPy arrays

## e.g. Remove Duplicates From A List in Python

It’s best to select a set if you want to store a unique collection of unordered items.

To create a set from any iterable, you can simply pass it to the built-in `set()` function. If you later need a real list again, you can similarly pass the set to the `list()` function.

Remember that an iterable can be a list, dictionary, … Check whether a variable is an iterable by applying the method `.__iter__` to it.

The following example clearly demonstrates the use of `set()` to delete all duplicates from your list:


```{python}
# Your list with duplicate values
duplicates = [1, 2, 3, 1, 2, 5, 6, 7, 8]

# Print the unique `duplicates` list
print(list(set(duplicates)))

# A list with small numbers 
smallNumbers = [1, 2, 3]

# Print the unique `duplicates` list without the small numbers
list(set(duplicates) - set(smallNumbers))
```

Notice that the original order of your list is not maintained after you remove the set elements of `smallNumbers`. As you already know by now, sets themselves are unordered collections, so any order that you had in your list is lost. When you convert your set back to a list, an arbitrary order is created for you.


## Why NumPy Instead Of Python Lists?

We use `NumPy` arrays instead of lists in Python since they...

- ... are more compact than lists,
- ... are faster in reading and writing,
- ... are more convenient given the quite of vector and matrix operations,
- ... are implemented more efficiently under-the-hood.

## Create an empty Numpy array

An empty NumPy array:

```{python}
import numpy as np
np.array([])
```

Initialize a NumPy array

```{python}
# Make a NumPy array of four rows and two columns and filled with 0
np.zeros(shape=(4,2))

# Make a NumPy array of 1 values of three columns
np.ones(3)

# Make an empty NumPy array
np.empty(shape=(0,0))

```

## Sum lists element-wise

```{python}

list1=[1, 2, 3]

list2=[4, 5, 6]

from operator import add
print(list(map(add, list1, list2)))

```

Note: you need to use `list()` to print the result of the `map()` function.

or, use `zip()` with a list comprehension.

```{python}
print([sum(x) for x in zip(list1, list2)])
```

Use NumPy

For larger data sets. Make sure that you import the numpy library and that your lists are converted into NumPy arrays.

```{python}
# Import numpy as np
import numpy as np

# Make your lists into NumPy arrays
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Element-wise addition
sum_vector = vector1 + vector2 

# Print the result
print(sum_vector)
```